### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by LordRatte** [ngkaho1234/Ext3Fsd#2]
Hi, there.

I just want to say thank you from the bottom of my heart. This is such a wonderful piece of software. You did here what Microsoft should have done long ago. This has made my life far easier.

Keep well. Joshua.

**Comment by ngkaho1234** [comment]
Oh.Thank you for your appreciation of our project. :) Hope you have a nice day. :D

Best,
Ka Ho Ng

**Comment by ngkaho1234** [comment]
Oh.Thank you for your
